//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloggerSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int CommentID { get; set; }
        [Required(ErrorMessage = "You must enter your Comment")]
        public string Context { get; set; }
        public int ArticleID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
